import { StyleSheet } from "react-native";

/** Edit Profile screen — matches Aether Arena mock (dark purple, cyan accents). */
export const colors = {
  screenBg: "#0F0C1D",
  inputBg: "#1B1528",
  labelMuted: "#9B8FB8",
  brandPurple: "#A855F7",
  neonCyan: "#22D3EE",
  successGreen: "#4ADE80",
  disabledBtn: "#2A1F3D",
  disabledBtnText: "#6B5F7A",
  activeTab: "#22D3EE",
  inactiveTab: "#E8E8E8",
  captionGrey: "#6B6578",
  ringGlow: "#06B6D4",
  cameraBtn: "#9333EA",
};

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.screenBg,
  },
  keyboard: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    minHeight: 48,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#2D1B4E",
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    gap: 8,
  },
  brandTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.brandPurple,
    letterSpacing: 0.5,
  },
  editLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.labelMuted,
    letterSpacing: 1,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: colors.ringGlow,
  },
  avatarBlock: {
    alignItems: "center",
    marginBottom: 28,
  },
  ringOuter: {
    width: 200,
    height: 200,
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.ringGlow,
    shadowOpacity: 0.85,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 16,
    borderWidth: 3,
    borderColor: colors.ringGlow,
  },
  avatarImage: {
    width: 184,
    height: 184,
    borderRadius: 92,
    backgroundColor: colors.inputBg,
  },
  cameraFab: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.cameraBtn,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: colors.screenBg,
  },
  fieldBlock: {
    marginBottom: 18,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  labelText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.labelMuted,
    letterSpacing: 0.8,
  },
  input: {
    backgroundColor: colors.inputBg,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#2A2238",
  },
  inputGamer: {
    color: colors.neonCyan,
    fontWeight: "600",
  },
  usernameAvailable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  usernameAvailableText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.successGreen,
    letterSpacing: 0.6,
  },
  errorBanner: {
    color: "#F87171",
    fontSize: 13,
    marginBottom: 12,
    textAlign: "center",
  },
  formError: {
    color: "#F87171",
    fontSize: 12,
    marginBottom: 8,
  },
  saveSection: {
    marginTop: 12,
    paddingBottom: 8,
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: colors.cameraBtn,
    paddingVertical: 16,
    borderRadius: 12,
  },
  saveBtnDisabled: {
    backgroundColor: colors.disabledBtn,
  },
  saveBtnText: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  saveBtnTextDisabled: {
    color: colors.disabledBtnText,
  },
  footerCaption: {
    marginTop: 12,
    textAlign: "center",
    fontSize: 10,
    fontWeight: "600",
    color: colors.captionGrey,
    letterSpacing: 0.8,
  },
  loadingBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
});
