import { colors } from "@/src/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: colors.screenBackground,
  },
  keyboard: {
    flex: 1,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    paddingTop: 8,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
    minHeight: 48,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.darkBackground1,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCenter: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 8,
    gap: 8,
  },
  brandTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: colors.primaryPurple,
    letterSpacing: 0.5,
  },
  editLabel: {
    fontSize: 11,
    fontWeight: "600",
    color: colors.grey,
    letterSpacing: 1,
  },
  headerAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: colors.neonBlue,
  },
  avatarBlock: {
    alignItems: "center",
    marginBottom: 28,
  },
  ringOuter: {
    width: 200,
    height: 200,
    borderRadius: 100,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: colors.neonBlue,
    shadowOpacity: 0.85,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 0 },
    elevation: 16,
    borderWidth: 3,
    borderColor: colors.neonBlue,
  },
  avatarImage: {
    width: 184,
    height: 184,
    borderRadius: 92,
    backgroundColor: colors.darkBackground2,
  },
  cameraFab: {
    position: "absolute",
    right: 8,
    bottom: 8,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primaryPurple,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 3,
    borderColor: colors.screenBackground,
  },
  fieldBlock: {
    marginBottom: 18,
  },
  labelRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
  },
  labelText: {
    fontSize: 11,
    fontWeight: "700",
    color: colors.grey,
    letterSpacing: 0.8,
  },
  input: {
    backgroundColor: colors.darkBackground2,
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
    fontSize: 15,
    color: colors.white,
    borderWidth: 1,
    borderColor: colors.darkBackground1,
  },
  inputGamer: {
    color: colors.neonBlue,
    fontWeight: "600",
  },
  usernameAvailable: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  usernameAvailableText: {
    fontSize: 11,
    fontWeight: "800",
    color: colors.neonBlue,
    letterSpacing: 0.6,
  },
  errorBanner: {
    color: colors.error,
    fontSize: 13,
    marginBottom: 12,
    textAlign: "center",
  },
  formError: {
    color: colors.error,
    fontSize: 12,
    marginBottom: 8,
  },
  saveSection: {
    marginTop: 12,
    paddingBottom: 8,
  },
  saveBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: colors.primaryPurple,
    paddingVertical: 16,
    borderRadius: 12,
  },
  saveBtnDisabled: {
    backgroundColor: colors.darkBackground2,
  },
  saveBtnText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.white,
    letterSpacing: 1,
  },
  saveBtnTextDisabled: {
    color: colors.grey,
  },
  footerCaption: {
    marginTop: 12,
    textAlign: "center",
    fontSize: 10,
    fontWeight: "600",
    color: colors.grey,
    letterSpacing: 0.8,
  },
  loadingBox: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
  },
});
