/** Arabic UI copy for the Tournaments tab (import from `strings`, not English literals). */
export const tournamentsAr = {
  screenTitle: "كينيتك أرينا",
  shareMessage: "كينيتك أرينا — البطولات والفعاليات المباشرة.",
  shareTitle: "كينيتك أرينا",
  backA11y: "رجوع",
  shareA11y: "مشاركة",
  liveOperations: "عمليات مباشرة",
  activeEvents: "فعاليات نشطة",
  archive: "أرشيف",
  pastEvents: "فعاليات سابقة",
  retry: "إعادة المحاولة",
  searchPlaceholder: "ابحث بالعنوان أو اسم البطل…",
  noActiveEvents: "لا توجد فعاليات نشطة",
  noPastEvents: "لا توجد فعاليات سابقة",
  noMatches: "لا نتائج مطابقة",
  openEntry: "التسجيل مفتوح",
  countdown: "العد التنازلي",
  participants: "المشاركون",
  join: "انضم",
  joinA11y: "انضمام إلى البطولة",
  loadingGate: "جاري التحميل…",
  replayBracket: "إعادة عرض الجدول",
  replayA11y: "إعادة عرض الجدول",
  champion: "البطل",
  winnerPrefix: "الفائز:",
  noWinner: "—",
} as const;
