import { StyleSheet } from "react-native";

/** Tournament registration — matches Aether Arena mock (#110B1D, purple / cyan). */
export const trColors = {
  bg: "#110B1D",
  cardBg: "#1A1225",
  inputBg: "#231830",
  labelMuted: "#8B7FA3",
  cyan: "#06B6D4",
  purple: "#A855F7",
  purpleDeep: "#7C3AED",
  white: "#FFFFFF",
  progressTrack: "#2D2438",
};

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: trColors.bg,
  },
  rootLoading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: trColors.bg,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 28,
  },
  headerRow: {
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: trColors.inputBg,
    alignItems: "center",
    justifyContent: "center",
  },
  backButtonSpacer: {
    width: 36,
    height: 36,
  },
  backIcon: {
    color: trColors.white,
    fontSize: 20,
    fontWeight: "700",
  },
  pageTitle: {
    color: trColors.white,
    fontSize: 17,
    fontWeight: "700",
  },
  heroCard: {
    borderRadius: 14,
    overflow: "hidden",
    backgroundColor: trColors.cardBg,
    marginBottom: 20,
  },
  heroImage: {
    width: "100%",
    height: 168,
    backgroundColor: "#0a0612",
  },
  heroImageOverlayTop: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: "flex-start",
    alignItems: "center",
    paddingTop: 10,
  },
  heroPubgPill: {
    backgroundColor: "rgba(0,0,0,0.55)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 6,
  },
  heroPubgText: {
    color: trColors.white,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 1,
  },
  heroLiveBadge: {
    position: "absolute",
    bottom: 12,
    left: 12,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: trColors.purple,
  },
  heroLiveText: {
    color: trColors.white,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  heroBody: {
    paddingHorizontal: 14,
    paddingVertical: 14,
    gap: 8,
  },
  heroTitle: {
    color: trColors.white,
    fontSize: 17,
    fontWeight: "800",
    letterSpacing: 0.4,
    lineHeight: 22,
  },
  heroSubtitle: {
    color: trColors.cyan,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.5,
  },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 4,
  },
  progressLabel: {
    color: trColors.labelMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  progressCount: {
    color: trColors.white,
    fontSize: 12,
    fontWeight: "700",
  },
  progressTrack: {
    height: 8,
    borderRadius: 4,
    backgroundColor: trColors.progressTrack,
    marginTop: 8,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 4,
    backgroundColor: trColors.cyan,
  },
  progressSub: {
    marginTop: 6,
    color: trColors.purple,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.6,
    textAlign: "center",
  },
  joinButtonWrap: {
    borderRadius: 12,
    overflow: "hidden",
    marginBottom: 18,
  },
  joinButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    paddingVertical: 16,
  },
  joinButtonDisabled: {
    opacity: 0.45,
  },
  joinButtonText: {
    color: trColors.white,
    fontSize: 14,
    fontWeight: "800",
    letterSpacing: 1.2,
  },
  fieldBlock: {
    marginBottom: 16,
  },
  fieldLabel: {
    color: trColors.labelMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.9,
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: trColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#332944",
    paddingHorizontal: 14,
    paddingVertical: 14,
    color: trColors.white,
    fontSize: 15,
  },
  selectField: {
    backgroundColor: trColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#332944",
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectFieldText: {
    color: trColors.white,
    fontSize: 15,
    flex: 1,
  },
  boolRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  checkBox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: "#4B3D63",
    backgroundColor: trColors.inputBg,
    alignItems: "center",
    justifyContent: "center",
  },
  checkBoxOn: {
    borderColor: trColors.cyan,
    backgroundColor: trColors.cyan,
  },
  termsText: {
    flex: 1,
    color: trColors.labelMuted,
    fontSize: 12,
    lineHeight: 18,
  },
  inviteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 8,
    marginBottom: 12,
  },
  inviteTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  inviteTitle: {
    color: trColors.white,
    fontSize: 17,
    fontWeight: "700",
  },
  selectedBadge: {
    backgroundColor: "#0E7490",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  selectedBadgeText: {
    color: trColors.white,
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: trColors.inputBg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#332944",
    paddingHorizontal: 12,
    marginBottom: 12,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    color: trColors.white,
    fontSize: 14,
  },
  friendRow: {
    backgroundColor: trColors.inputBg,
    borderRadius: 10,
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#332944",
  },
  friendRowBlocked: {
    opacity: 0.55,
  },
  friendAvatar: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: "#3D3450",
    marginRight: 12,
  },
  friendTextWrap: {
    flex: 1,
  },
  friendName: {
    color: trColors.white,
    fontSize: 16,
    fontWeight: "700",
  },
  friendStatus: {
    color: trColors.cyan,
    fontSize: 12,
    marginTop: 2,
    fontWeight: "500",
  },
  selectCircle: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 2,
    borderColor: "#5B4D72",
    alignItems: "center",
    justifyContent: "center",
  },
  selectCircleActive: {
    borderColor: trColors.cyan,
    backgroundColor: trColors.cyan,
  },
  viewAllFriends: {
    marginTop: 8,
    marginBottom: 8,
    alignItems: "center",
    paddingVertical: 8,
  },
  viewAllFriendsText: {
    color: trColors.cyan,
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 0.6,
  },
  loadingMoreWrap: {
    paddingVertical: 12,
    alignItems: "center",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.55)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: trColors.cardBg,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    paddingBottom: 24,
    maxHeight: "55%",
  },
  modalOption: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#332944",
  },
  modalOptionText: {
    color: trColors.white,
    fontSize: 16,
  },
});
