import { colors_V2 } from "@/src/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors_V2.background,
  },
  headerWrap: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
    backgroundColor: colors_V2.background,
    gap: 14,
  },
  headerRow: {
    alignItems: "center",
    gap: 12,
  },
  headerIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors_V2.card,
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  headerAvatar: {
    width: 34,
    height: 34,
    borderRadius: 10,
  },
  headerAvatarPlaceholder: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "rgba(216,185,255,0.18)",
  },
  headerTitle: {
    flex: 1,
    color: colors_V2.textPrimary,
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.4,
    textAlign: "right",
    writingDirection: "rtl",
  },
  headerNotifButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  tabsWrap: {
    backgroundColor: colors_V2.card,
    borderRadius: 12,
    padding: 6,
    gap: 6,
  },
  tabButton: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: colors_V2.primary,
  },
  tabLabel: {
    color: colors_V2.textSecondary,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    writingDirection: "rtl",
  },
  tabLabelActive: {
    color: colors_V2.textPrimary,
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
  },
  root: {
    flex: 1,
  },
  listWrap: {
    flex: 1,
    minHeight: 0,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  text: {
    fontSize: 18,
    color: colors_V2.textPrimary,
    textAlign: "center",
    writingDirection: "rtl",
  },
  muted: {
    fontSize: 14,
    color: colors_V2.textSecondary,
    textAlign: "center",
    marginTop: 8,
    writingDirection: "rtl",
  },
  retryText: {
    marginTop: 10,
    color: colors_V2.primaryLight,
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    writingDirection: "rtl",
  },
  reelPageFull: {
    alignSelf: "center",
    backgroundColor: colors_V2.background,
    overflow: "hidden",
  },
  videoShell: {
    flex: 1,
    width: "100%",
    minHeight: 0,
    backgroundColor: colors_V2.background,
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: "rgba(216,185,255,0.08)",
  },
  videoPlayerStack: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  videoTapLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  playOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  playIconWrap: {
    alignItems: "center",
    justifyContent: "center",
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(0,0,0,0.42)",
  },
  video: {
    ...StyleSheet.absoluteFillObject,
  },
  videoPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors_V2.card,
  },
  videoPlaceholderText: {
    color: colors_V2.textSecondary,
    fontSize: 14,
    writingDirection: "rtl",
  },
  overlayBottomLeft: {
    position: "absolute",
    left: 14,
    right: 92,
    bottom: 26,
    zIndex: 3,
    justifyContent: "flex-end",
  },
  overlayTextContent: {
    position: "relative",
    gap: 1,
    maxWidth: "100%",
  },
  reelAuthor: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: "700",
    color: colors_V2.textPrimary,
    textAlign: "left",
  },
  reelTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors_V2.textPrimary,
    lineHeight: 16,
    letterSpacing: 0,
    marginBottom: 0,
    textAlign: "left",
  },
  reelDescription: {
    fontSize: 11,
    lineHeight: 14,
    color: colors_V2.textPrimary,
    textAlign: "left",
  },
  descriptionBlock: {
    marginTop: 1,
    maxWidth: "100%",
  },
  moreLessPressable: {
    alignSelf: "flex-start",
    marginTop: 1,
  },
  moreText: {
    fontSize: 10,
    lineHeight: 12,
    fontWeight: "600",
    color: colors_V2.textPrimary,
  },
  overlayRight: {
    position: "absolute",
    right: 16,
    bottom: 96,
    alignItems: "center",
    gap: 10,
    zIndex: 3,
  },
  overlayAction: {
    alignItems: "center",
    justifyContent: "center",
    gap: 1,
  },
  bottomChrome: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
  },
  overlayCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "transparent",
    borderWidth: 0,
    alignItems: "center",
    justifyContent: "center",
    overflow: "visible",
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },
  overlayCircleActive: {
    backgroundColor: "transparent",
    borderColor: "transparent",
    shadowColor: "transparent",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
  },

  likedGlow: {
    position: "absolute",
    width: 86,
    height: 86,
    borderRadius: 22,
    top: -19,
    left: -19,
    zIndex: 0,
    opacity: 1,
    // Make sure the gradient itself doesn't block presses
    pointerEvents: "none",
  },
  overlayCount: {
    color: colors_V2.textPrimary,
    fontSize: 10,
    fontWeight: "500",
    textAlign: "center",
  },
  progressTrack: {
    height: 2,
    width: "100%",
    backgroundColor: "rgba(216,185,255,0.12)",
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors_V2.primaryLight,
  },
  modalBackdropHost: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalKeyboardHost: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalSheet: {
    maxHeight: "72%",
    backgroundColor: colors_V2.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 8,
  },
  modalGrab: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors_V2.textSecondary,
    marginTop: 8,
    marginBottom: 12,
  },
  modalHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  modalTitleRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors_V2.textPrimary,
    writingDirection: "rtl",
  },
  modalCountBadge: {
    backgroundColor: colors_V2.background,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  modalCountText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors_V2.textSecondary,
  },
  modalClose: {
    padding: 8,
  },
  modalCloseText: {
    color: colors_V2.textPrimary,
    fontSize: 18,
    fontWeight: "600",
  },
  modalList: {
    flexGrow: 0,
    maxHeight: 320,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  mentionLoading: {
    color: colors_V2.textSecondary,
    fontSize: 13,
    textAlign: "right",
    writingDirection: "rtl",
  },
  commentRow: {
    marginBottom: 12,
  },
  commentCard: {
    backgroundColor: "rgba(255,255,255,0.03)",
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.1)",
    borderRadius: 12,
    padding: 12,
    alignItems: "flex-start",
  },
  commentTextGroup: {
    flex: 1,
    marginRight: 10,
    alignItems: "flex-end",
  },
  commentRowFocused: {
    borderWidth: 1,
    borderColor: colors_V2.primaryLight,
    borderRadius: 10,
    padding: 8,
    backgroundColor: "rgba(147,204,255,0.08)",
  },
  commentMeta: {
    // legacy
  },
  commentUser: {
    fontSize: 14,
    fontWeight: "700",
    color: colors_V2.textPrimary,
    marginBottom: 4,
  },
  commentTime: {
    fontSize: 11,
    fontWeight: "500",
    color: colors_V2.textSecondary,
  },
  commentBody: {
    fontSize: 13,
    color: colors_V2.textSecondary,
    lineHeight: 18,
    textAlign: "right",
  },
  commentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors_V2.background,
  },
  commentRowInner: {
    // legacy
  },
  modalInputRow: {
    alignItems: "center",
    backgroundColor: colors_V2.background,
    // borderRadius: 24,
    
    padding: 12,
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  modalInputAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors_V2.primary,
  },
  modalInputWrap: {
    flex: 1,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors_V2.background,
    borderRadius: 22,
    paddingLeft: 4,
    paddingRight: 14,
    minHeight: 44,
  },
  modalInput: {
    flex: 1,
    borderColor:colors_V2.card,
    borderWidth: 1,
    borderRadius: 22,
    color: colors_V2.textPrimary,
    fontSize: 14,
    paddingVertical: 8,
    textAlign: "right",
    writingDirection: "rtl",
  },
  modalSend: {
    padding: 8,
  },
  modalSendText: {
    display: "none",
  },
  mentionHitsWrap: {
    marginTop: 10,
    marginHorizontal: 12,
    gap: 8,
  },
  mentionHitItem: {
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.2)",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  mentionHitLabel: {
    color: colors_V2.primaryLight,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
    writingDirection: "rtl",
  },
  votingStateWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 10,
  },
  votingStateText: {
    color: colors_V2.textPrimary,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
    writingDirection: "rtl",
  },
  votingListContent: {
    paddingHorizontal: 16,
    paddingBottom: 28,
    gap: 16,
  },
  pollCard: {
    backgroundColor: colors_V2.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.08)",
    marginBottom: 16,
  },
  pollHeaderRow: {
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  pollHeaderMain: {
    flex: 1,
    minWidth: 0,
  },
  pollTitle: {
    color: colors_V2.textPrimary,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "right",
    writingDirection: "rtl",
  },
  pollDescription: {
    color: colors_V2.textSecondary,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "right",
    writingDirection: "rtl",
  },
  liveBadgeWrap: {
    backgroundColor: "rgba(147,204,255,0.12)",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  liveBadgeText: {
    color: colors_V2.primaryLight,
    fontSize: 11,
    fontWeight: "800",
    writingDirection: "rtl",
  },
  pollOptionsList: {
    gap: 10,
  },
  pollOptionCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pollOptionCardSelected: {
    borderColor: colors_V2.primaryLight,
    backgroundColor: "rgba(147,204,255,0.14)",
    opacity: 1,
  },
  /** After vote: options the user did not pick. */
  pollOptionCardInactive: {
    opacity: 0.42,
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(216,185,255,0.06)",
  },
  pollOptionRow: {
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  pollOptionLabelWrap: {
    flex: 1,
    minWidth: 0,
  },
  pollOptionLabel: {
    color: colors_V2.textPrimary,
    fontSize: 16,
    fontWeight: "700",
    textAlign: "right",
    writingDirection: "rtl",
  },
  pollOptionLabelSelected: {
    color: colors_V2.primaryLight,
  },
  pollOptionLabelInactive: {
    color: colors_V2.textSecondary,
    opacity: 0.85,
  },
  pollOptionRight: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
  },
  selectedDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors_V2.primaryLight,
  },
  unselectedDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.18)",
  },
  pollOptionPercent: {
    color: colors_V2.textSecondary,
    fontSize: 14,
    fontWeight: "800",
  },
  pollOptionPercentSelected: {
    color: colors_V2.textPrimary,
  },
  pollOptionPercentInactive: {
    color: colors_V2.textSecondary,
    opacity: 0.7,
  },
  pollOptionDotInactive: {
    opacity: 0.35,
  },
  pollEmptyText: {
    color: colors_V2.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "right",
    writingDirection: "rtl",
  },
  pollFooterRow: {
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    gap: 10,
  },
  pollFooterText: {
    color: colors_V2.textSecondary,
    fontSize: 12,
    fontWeight: "600",
    writingDirection: "rtl",
  },
  pollFooterLocked: {
    color: colors_V2.primaryLight,
    fontSize: 12,
    fontWeight: "700",
    writingDirection: "rtl",
  },
});
