import { colors_V2 } from "@/src/theme/colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors_V2.background,
  },
  headerWrap: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 10,
    backgroundColor: colors_V2.background,
    gap: 14,
  },
  headerRow: {
    alignItems: "center",
    gap: 12,
  },
  headerIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors_V2.card,
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  headerAvatar: {
    width: 34,
    height: 34,
    borderRadius: 10,
  },
  headerAvatarPlaceholder: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: "rgba(216,185,255,0.18)",
  },
  headerTitle: {
    flex: 1,
    color: colors_V2.lilac,
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 0.4,
    textAlign: "right",
    writingDirection: "rtl",
  },
  headerNotifButton: {
    width: 36,
    height: 36,
    alignItems: "center",
    justifyContent: "center",
  },
  tabsWrap: {
    backgroundColor: colors_V2.card,
    borderRadius: 12,
    padding: 6,
    gap: 6,
  },
  tabButton: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  tabButtonActive: {
    backgroundColor: colors_V2.purple,
  },
  tabLabel: {
    color: colors_V2.dustyLavender,
    fontSize: 15,
    fontWeight: "800",
    textAlign: "center",
    writingDirection: "rtl",
  },
  tabLabelActive: {
    color: colors_V2.lilac,
  },
  contentArea: {
    flex: 1,
    minHeight: 0,
  },
  root: {
    flex: 1,
  },
  listWrap: {
    flex: 1,
    minHeight: 0,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  text: {
    fontSize: 18,
    color: colors_V2.lilac,
    textAlign: "center",
    writingDirection: "rtl",
  },
  muted: {
    fontSize: 14,
    color: colors_V2.slate,
    textAlign: "center",
    marginTop: 8,
    writingDirection: "rtl",
  },
  retryText: {
    marginTop: 10,
    color: colors_V2.skyBlue,
    fontSize: 14,
    fontWeight: "700",
    textAlign: "center",
    writingDirection: "rtl",
  },
  reelPageFull: {
    alignSelf: "center",
    backgroundColor: colors_V2.background,
    overflow: "hidden",
  },
  videoShell: {
    flex: 1,
    width: "100%",
    minHeight: 0,
    backgroundColor: colors_V2.background,
    overflow: "hidden",
    borderTopWidth: 1,
    borderTopColor: "rgba(216,185,255,0.08)",
  },
  videoPlayerStack: {
    ...StyleSheet.absoluteFillObject,
    overflow: "hidden",
  },
  videoTapLayer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2,
  },
  video: {
    ...StyleSheet.absoluteFillObject,
  },
  videoOverlay: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 1,
    pointerEvents: "none",
  },
  videoPlaceholder: {
    ...StyleSheet.absoluteFillObject,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors_V2.card,
  },
  videoPlaceholderText: {
    color: colors_V2.slate,
    fontSize: 14,
    writingDirection: "rtl",
  },
  overlayBottomLeft: {
    position: "absolute",
    left: 18,
    right: 94,
    bottom: 56,
    zIndex: 3,
    justifyContent: "flex-end",
  },
  reelTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: colors_V2.lilac,
    lineHeight: 34,
    letterSpacing: 0.1,
    marginBottom: 12,
    textShadowColor: "rgba(0,0,0,0.55)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 10,
    textAlign: "left",
  },
  reelDescription: {
    fontSize: 15,
    lineHeight: 24,
    color: colors_V2.lilac,
    textShadowColor: "rgba(0,0,0,0.5)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
    textAlign: "left",
  },
  descriptionBlock: {
    marginTop: 8,
    maxWidth: "100%",
  },
  moreLessPressable: {
    alignSelf: "flex-start",
    marginTop: 6,
  },
  moreText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    color: colors_V2.skyBlue,
  },
  commentPreviewDragHost: {
    alignSelf: "flex-start",
    marginBottom: 18,
    maxWidth: "100%",
  },
  commentPreview: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
    maxWidth: "100%",
    backgroundColor: "rgba(35,22,46,0.78)",
    borderStartWidth: 2,
    borderStartColor: colors_V2.skyBlue,
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 10,
    minWidth: 220,
    borderWidth: 1,
    borderColor: "rgba(147,204,255,0.18)",
    shadowColor: colors_V2.skyBlue,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 8,
  },
  /** Avatar + username as one tight cluster (RTL: avatar at visual right, name beside it). */
  commentPreviewIdentity: {
    flexDirection: "row",
    alignItems: "center",
    flexShrink: 0,
    gap: 6,
    maxWidth: "46%",
  },
  commentPreviewBodyWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: "center",
  },
  commentPreviewAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors_V2.card,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(147,204,255,0.28)",
  },
  commentPreviewAvatarPlaceholder: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(216,185,255,0.14)",
    borderWidth: 1,
    borderColor: "rgba(147,204,255,0.35)",
  },
  commentPreviewUser: {
    fontSize: 14,
    fontWeight: "700",
    color: colors_V2.skyBlue,
    lineHeight: 18,
    textShadowColor: "rgba(147,204,255,0.45)",
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
    flexShrink: 1,
    writingDirection: "rtl",
    textAlign: "right",
  },
  commentPreviewBody: {
    fontSize: 14,
    color: colors_V2.lilac,
    lineHeight: 18,
    opacity: 0.96,
    writingDirection: "rtl",
    textAlign: "right",
  },
  commentPreviewBodyPrefix: {
    fontSize: 14,
    lineHeight: 18,
    color: colors_V2.slate,
    fontWeight: "600",
    writingDirection: "rtl",
  },
  overlayRight: {
    position: "absolute",
    right: 16,
    bottom: 104,
    alignItems: "center",
    gap: 18,
    zIndex: 3,
  },
  bottomChrome: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 2,
  },
  overlayAction: {
    alignItems: "center",
    gap: 6,
  },
  overlayCircle: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: "rgba(35,22,46,0.92)",
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  overlayCount: {
    color: colors_V2.lilac,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  progressTrack: {
    height: 2,
    width: "100%",
    backgroundColor: "rgba(216,185,255,0.12)",
  },
  progressFill: {
    height: "100%",
    backgroundColor: colors_V2.skyBlue,
  },
  modalBackdropHost: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalKeyboardHost: {
    flex: 1,
    justifyContent: "flex-end",
  },
  modalSheet: {
    maxHeight: "72%",
    backgroundColor: colors_V2.card,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 8,
  },
  modalGrab: {
    alignSelf: "center",
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors_V2.slate,
    marginTop: 8,
    marginBottom: 12,
  },
  modalHeader: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(255,255,255,0.08)",
  },
  modalTitleRow: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors_V2.lilac,
    writingDirection: "rtl",
  },
  modalCountBadge: {
    backgroundColor: colors_V2.background,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  modalCountText: {
    fontSize: 12,
    fontWeight: "600",
    color: colors_V2.slate,
  },
  modalClose: {
    padding: 8,
  },
  modalCloseText: {
    color: colors_V2.lilac,
    fontSize: 18,
    fontWeight: "600",
  },
  modalList: {
    flexGrow: 0,
    maxHeight: 320,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  commentRow: {
    marginBottom: 16,
  },
  commentRowFocused: {
    borderWidth: 1,
    borderColor: colors_V2.skyBlue,
    borderRadius: 10,
    padding: 8,
    backgroundColor: "rgba(147,204,255,0.08)",
  },
  commentMeta: {
    flexDirection: "row-reverse",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  commentUser: {
    fontSize: 14,
    fontWeight: "700",
    color: colors_V2.lilac,
    writingDirection: "rtl",
  },
  commentTime: {
    fontSize: 11,
    fontWeight: "600",
    color: colors_V2.slate,
    writingDirection: "rtl",
  },
  commentBody: {
    fontSize: 14,
    color: colors_V2.dustyLavender,
    lineHeight: 20,
    writingDirection: "rtl",
    textAlign: "right",
  },
  commentAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors_V2.background,
    marginLeft: 10,
  },
  commentRowInner: {
    flexDirection: "row-reverse",
  },
  modalInputRow: {
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 12,
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(255,255,255,0.08)",
  },
  modalInputAvatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors_V2.purple,
  },
  modalInputWrap: {
    flex: 1,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors_V2.background,
    borderRadius: 22,
    paddingLeft: 4,
    paddingRight: 14,
    minHeight: 44,
  },
  modalInput: {
    flex: 1,
    color: colors_V2.lilac,
    fontSize: 14,
    paddingVertical: 8,
    textAlign: "right",
    writingDirection: "rtl",
  },
  modalSend: {
    backgroundColor: colors_V2.purple,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 16,
  },
  modalSendText: {
    color: colors_V2.lilac,
    fontWeight: "800",
    fontSize: 12,
  },
  mentionHitsWrap: {
    marginTop: 10,
    marginHorizontal: 12,
    gap: 8,
  },
  mentionHitItem: {
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.2)",
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 10,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  mentionHitLabel: {
    color: colors_V2.skyBlue,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "right",
    writingDirection: "rtl",
  },
  votingStateWrap: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 24,
    gap: 10,
  },
  votingStateText: {
    color: colors_V2.lilac,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
    writingDirection: "rtl",
  },
  votingListContent: {
    paddingHorizontal: 16,
    paddingBottom: 28,
    gap: 16,
  },
  pollCard: {
    backgroundColor: colors_V2.card,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.08)",
    marginBottom: 16,
  },
  pollHeaderRow: {
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  pollHeaderMain: {
    flex: 1,
    minWidth: 0,
  },
  pollTitle: {
    color: colors_V2.lilac,
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "right",
    writingDirection: "rtl",
  },
  pollDescription: {
    color: colors_V2.dustyLavender,
    fontSize: 13,
    lineHeight: 20,
    textAlign: "right",
    writingDirection: "rtl",
  },
  liveBadgeWrap: {
    backgroundColor: "rgba(147,204,255,0.12)",
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  liveBadgeText: {
    color: colors_V2.skyBlue,
    fontSize: 11,
    fontWeight: "800",
    writingDirection: "rtl",
  },
  pollOptionsList: {
    gap: 10,
  },
  pollOptionCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "transparent",
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  pollOptionCardSelected: {
    borderColor: colors_V2.skyBlue,
    backgroundColor: "rgba(147,204,255,0.14)",
    opacity: 1,
  },
  /** After vote: options the user did not pick. */
  pollOptionCardInactive: {
    opacity: 0.42,
    backgroundColor: "rgba(0,0,0,0.28)",
    borderColor: "rgba(216,185,255,0.06)",
  },
  pollOptionRow: {
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  pollOptionLabelWrap: {
    flex: 1,
    minWidth: 0,
  },
  pollOptionLabel: {
    color: colors_V2.lilac,
    fontSize: 16,
    fontWeight: "700",
    textAlign: "right",
    writingDirection: "rtl",
  },
  pollOptionLabelSelected: {
    color: colors_V2.lavenderLight,
  },
  pollOptionLabelInactive: {
    color: colors_V2.slate,
    opacity: 0.85,
  },
  pollOptionRight: {
    flexDirection: "row-reverse",
    alignItems: "center",
    gap: 8,
  },
  selectedDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors_V2.lavenderLight,
  },
  unselectedDot: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: "rgba(216,185,255,0.18)",
  },
  pollOptionPercent: {
    color: colors_V2.slate,
    fontSize: 14,
    fontWeight: "800",
  },
  pollOptionPercentSelected: {
    color: colors_V2.lilac,
  },
  pollOptionPercentInactive: {
    color: colors_V2.slate,
    opacity: 0.7,
  },
  pollOptionDotInactive: {
    opacity: 0.35,
  },
  pollEmptyText: {
    color: colors_V2.slate,
    fontSize: 13,
    lineHeight: 18,
    textAlign: "right",
    writingDirection: "rtl",
  },
  pollFooterRow: {
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 14,
    gap: 10,
  },
  pollFooterText: {
    color: colors_V2.slate,
    fontSize: 12,
    fontWeight: "600",
    writingDirection: "rtl",
  },
  pollFooterLocked: {
    color: colors_V2.skyBlue,
    fontSize: 12,
    fontWeight: "700",
    writingDirection: "rtl",
  },
});
